# Generated by Django 4.1.7 on 2023-03-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('H', 'Homosexual'), ('B', 'Bisexual'), ('O', 'Other')], default='M', max_length=1),
        ),
    ]
